Search.appendIndex(
    [
                {
            "fqsen": "\\MatthiasMullie\\Geo\\Bounds",
            "name": "Bounds",
            "summary": "Please\u0020report\u0020bugs\u0020on\u0020https\u003A\/\/github.com\/matthiasmullie\/geo\/issues.",
            "url": "classes/MatthiasMullie-Geo-Bounds.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Bounds\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Bounds.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Bounds\u003A\u003A\u0024ne",
            "name": "ne",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Bounds.html#property_ne"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Bounds\u003A\u003A\u0024sw",
            "name": "sw",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Bounds.html#property_sw"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Cluster",
            "name": "Cluster",
            "summary": "Please\u0020report\u0020bugs\u0020on\u0020https\u003A\/\/github.com\/matthiasmullie\/geo\/issues.",
            "url": "classes/MatthiasMullie-Geo-Cluster.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Cluster\u003A\u003AaddCoordinate\u0028\u0029",
            "name": "addCoordinate",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Cluster.html#method_addCoordinate"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Cluster\u003A\u003A\u0024bounds",
            "name": "bounds",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Cluster.html#property_bounds"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Cluster\u003A\u003A\u0024center",
            "name": "center",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Cluster.html#property_center"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Cluster\u003A\u003A\u0024total",
            "name": "total",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Cluster.html#property_total"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Cluster\u003A\u003A\u0024coordinates",
            "name": "coordinates",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Cluster.html#property_coordinates"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Clusterer",
            "name": "Clusterer",
            "summary": "Please\u0020report\u0020bugs\u0020on\u0020https\u003A\/\/github.com\/matthiasmullie\/geo\/issues.",
            "url": "classes/MatthiasMullie-Geo-Clusterer.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Clusterer\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Clusterer.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Clusterer\u003A\u003AsetSaveCoordinates\u0028\u0029",
            "name": "setSaveCoordinates",
            "summary": "Enables\u0020coordinate\u0020saving\u0020in\u0020clusters.",
            "url": "classes/MatthiasMullie-Geo-Clusterer.html#method_setSaveCoordinates"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Clusterer\u003A\u003AsetMinClusterLocations\u0028\u0029",
            "name": "setMinClusterLocations",
            "summary": "Set\u0020the\u0020minimum\u0020amount\u0020of\u0020locations\u0020before\u0020clustering.",
            "url": "classes/MatthiasMullie-Geo-Clusterer.html#method_setMinClusterLocations"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Clusterer\u003A\u003AsetNumberOfClusters\u0028\u0029",
            "name": "setNumberOfClusters",
            "summary": "Set\u0020an\u0020approximate\u0020amount\u0020of\u0020clusters.",
            "url": "classes/MatthiasMullie-Geo-Clusterer.html#method_setNumberOfClusters"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Clusterer\u003A\u003AaddCoordinate\u0028\u0029",
            "name": "addCoordinate",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Clusterer.html#method_addCoordinate"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Clusterer\u003A\u003AgetCoordinates\u0028\u0029",
            "name": "getCoordinates",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Clusterer.html#method_getCoordinates"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Clusterer\u003A\u003AgetClusters\u0028\u0029",
            "name": "getClusters",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Clusterer.html#method_getClusters"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Coordinate",
            "name": "Coordinate",
            "summary": "Please\u0020report\u0020bugs\u0020on\u0020https\u003A\/\/github.com\/matthiasmullie\/geo\/issues.",
            "url": "classes/MatthiasMullie-Geo-Coordinate.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Coordinate\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Coordinate.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Coordinate\u003A\u003A\u0024latitude",
            "name": "latitude",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Coordinate.html#property_latitude"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Coordinate\u003A\u003A\u0024longitude",
            "name": "longitude",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Coordinate.html#property_longitude"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Coordinate\u003A\u003A\u0024data",
            "name": "data",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Coordinate.html#property_data"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Exception",
            "name": "Exception",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Exception.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Geo",
            "name": "Geo",
            "summary": "Please\u0020report\u0020bugs\u0020on\u0020https\u003A\/\/github.com\/matthiasmullie\/geo\/issues.",
            "url": "classes/MatthiasMullie-Geo-Geo.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Geo\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Geo.html#method___construct"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Geo\u003A\u003AsetRadius\u0028\u0029",
            "name": "setRadius",
            "summary": "Allows\u0020to\u0020override\u0020radius.",
            "url": "classes/MatthiasMullie-Geo-Geo.html#method_setRadius"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Geo\u003A\u003Adistance\u0028\u0029",
            "name": "distance",
            "summary": "",
            "url": "classes/MatthiasMullie-Geo-Geo.html#method_distance"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo\\Geo\u003A\u003Abounds\u0028\u0029",
            "name": "bounds",
            "summary": "This\u0020calculates\u0020the\u0020boundary\u0020at\u0020\u0024distance\u0020north,\u0020east,\u0020south\u0020\u0026\u0020west\u0020from\n\u0024coord.",
            "url": "classes/MatthiasMullie-Geo-Geo.html#method_bounds"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\MatthiasMullie\\Geo",
            "name": "Geo",
            "summary": "",
            "url": "namespaces/matthiasmullie-geo.html"
        },                {
            "fqsen": "\\MatthiasMullie",
            "name": "MatthiasMullie",
            "summary": "",
            "url": "namespaces/matthiasmullie.html"
        }            ]
);
